// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoMSD.Modelos;

#nullable disable

namespace ProyectoMSD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250921145815_Numero2")]
    partial class Numero2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProyectoMSD.Modelos.Almacenan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdDispositivos")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_Dispositivos");

                    b.Property<int>("IdEspacios")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_Espacios");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdDispositivos" }, "ID_Dispositivos");

                    b.HasIndex(new[] { "IdEspacios" }, "ID_Espacios");

                    b.ToTable("almacenan", (string)null);
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Configuracione", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Adaptador")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Alertas")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("Automatizacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdDispositivos")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_Dispositivos");

                    b.Property<int>("IdUsuarios")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_Usuarios");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Codigo")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdDispositivos" }, "ID_Dispositivos")
                        .HasDatabaseName("ID_Dispositivos1");

                    b.HasIndex(new[] { "IdUsuarios" }, "ID_Usuarios");

                    b.ToTable("configuraciones", (string)null);
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Dispositivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Usos")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("dispositivos", (string)null);
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Espacio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPropiedades")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_Propiedades");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Permisos")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Señal")
                        .HasColumnType("int(11)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPropiedades" }, "ID_Propiedades");

                    b.ToTable("espacios", (string)null);
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Propiedade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("IdUsuarios")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_USUARIOS");

                    b.Property<int>("Pisos")
                        .HasColumnType("int(11)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdUsuarios" }, "ID_USUARIOS");

                    b.ToTable("propiedades", (string)null);
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Soporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdUsuarios")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_USUARIOS");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdUsuarios" }, "ID_USUARIOS")
                        .HasDatabaseName("ID_USUARIOS1");

                    b.ToTable("soportes", (string)null);
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acesso")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<long?>("Documento")
                        .HasColumnType("bigint(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Permisos")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Rut")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Telefono")
                        .HasColumnType("int(11)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Almacenan", b =>
                {
                    b.HasOne("ProyectoMSD.Modelos.Dispositivo", "IdDispositivosNavigation")
                        .WithMany("Almacenans")
                        .HasForeignKey("IdDispositivos")
                        .IsRequired()
                        .HasConstraintName("almacenan_ibfk_2");

                    b.HasOne("ProyectoMSD.Modelos.Espacio", "IdEspaciosNavigation")
                        .WithMany("Almacenans")
                        .HasForeignKey("IdEspacios")
                        .IsRequired()
                        .HasConstraintName("almacenan_ibfk_1");

                    b.Navigation("IdDispositivosNavigation");

                    b.Navigation("IdEspaciosNavigation");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Configuracione", b =>
                {
                    b.HasOne("ProyectoMSD.Modelos.Dispositivo", "IdDispositivosNavigation")
                        .WithMany("Configuraciones")
                        .HasForeignKey("IdDispositivos")
                        .IsRequired()
                        .HasConstraintName("configuraciones_ibfk_1");

                    b.HasOne("ProyectoMSD.Modelos.Usuario", "IdUsuariosNavigation")
                        .WithMany("Configuraciones")
                        .HasForeignKey("IdUsuarios")
                        .IsRequired()
                        .HasConstraintName("configuraciones_ibfk_2");

                    b.Navigation("IdDispositivosNavigation");

                    b.Navigation("IdUsuariosNavigation");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Espacio", b =>
                {
                    b.HasOne("ProyectoMSD.Modelos.Propiedade", "IdPropiedadesNavigation")
                        .WithMany("Espacios")
                        .HasForeignKey("IdPropiedades")
                        .IsRequired()
                        .HasConstraintName("espacios_ibfk_1");

                    b.Navigation("IdPropiedadesNavigation");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Propiedade", b =>
                {
                    b.HasOne("ProyectoMSD.Modelos.Usuario", "IdUsuariosNavigation")
                        .WithMany("Propiedades")
                        .HasForeignKey("IdUsuarios")
                        .IsRequired()
                        .HasConstraintName("propiedades_ibfk_1");

                    b.Navigation("IdUsuariosNavigation");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Soporte", b =>
                {
                    b.HasOne("ProyectoMSD.Modelos.Usuario", "IdUsuariosNavigation")
                        .WithMany("Soportes")
                        .HasForeignKey("IdUsuarios")
                        .IsRequired()
                        .HasConstraintName("soportes_ibfk_1");

                    b.Navigation("IdUsuariosNavigation");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Dispositivo", b =>
                {
                    b.Navigation("Almacenans");

                    b.Navigation("Configuraciones");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Espacio", b =>
                {
                    b.Navigation("Almacenans");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Propiedade", b =>
                {
                    b.Navigation("Espacios");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Usuario", b =>
                {
                    b.Navigation("Configuraciones");

                    b.Navigation("Propiedades");

                    b.Navigation("Soportes");
                });
#pragma warning restore 612, 618
        }
    }
}
