// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoMSD.Modelos;

#nullable disable

namespace ProyectoMSD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318025442_AddUbicacionesMap")]
    partial class AddUbicacionesMap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProyectoMSD.Modelos.Almacenan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdDispositivos")
                        .HasColumnType("int");

                    b.Property<int>("IdDispositivosNavigationId")
                        .HasColumnType("int(11)");

                    b.Property<int>("IdEspacios")
                        .HasColumnType("int");

                    b.Property<int>("IdEspaciosNavigationId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("IdDispositivosNavigationId");

                    b.HasIndex("IdEspaciosNavigationId");

                    b.ToTable("Almacenan");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Configuracione", b =>
                {
                    b.Property<int>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Codigo"));

                    b.Property<string>("Adaptador")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Alertas")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<bool>("Automatizacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("IdDispositivos")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_Dispositivos");

                    b.Property<int>("IdUsuarios")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_Usuarios");

                    b.Property<int>("IdUsuariosNavigationId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Idioma")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Codigo")
                        .HasName("PRIMARY");

                    b.HasIndex("IdUsuariosNavigationId");

                    b.HasIndex(new[] { "IdDispositivos" }, "ID_Dispositivos");

                    b.HasIndex(new[] { "IdUsuarios" }, "ID_Usuarios");

                    b.ToTable("configuraciones", (string)null);
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Dispositivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("IdEspacio")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_Espacio");

                    b.Property<string>("MAC_Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Usos")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("IdEspacio");

                    b.ToTable("dispositivos", (string)null);
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Espacio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPropiedades")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_Propiedades");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Permisos")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Señal")
                        .HasColumnType("int(11)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("UbicacioneId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("UbicacioneId");

                    b.HasIndex(new[] { "IdPropiedades" }, "ID_Propiedades");

                    b.ToTable("espacios", (string)null);
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime");

                    b.Property<int>("IdUsuarios")
                        .HasColumnType("int(11)")
                        .HasColumnName("IdUsuarios");

                    b.Property<bool>("Leida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RutaRedireccion")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("IdUsuarios");

                    b.ToTable("notificaciones", (string)null);
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Propiedade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("IdUsuarios")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_USUARIOS");

                    b.Property<int>("IdUsuariosNavigationId")
                        .HasColumnType("int(11)");

                    b.Property<int>("Pisos")
                        .HasColumnType("int(11)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("UbicacioneId")
                        .HasColumnType("int(11)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("IdUsuariosNavigationId");

                    b.HasIndex("UbicacioneId");

                    b.HasIndex(new[] { "IdUsuarios" }, "ID_USUARIOS");

                    b.ToTable("propiedades", (string)null);
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.RegistroAcceso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("Direccion_Ip");

                    b.Property<int?>("DuracionSesion")
                        .HasColumnType("int(11)")
                        .HasColumnName("Duracion_Sesion");

                    b.Property<DateTime>("FechaAcceso")
                        .HasColumnType("datetime");

                    b.Property<int>("IdUsuarios")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_Usuarios");

                    b.Property<string>("Navegador")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PaginaVisitada")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Pagina_Visitada");

                    b.Property<string>("TipoAccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdUsuarios" }, "ID_Usuarios")
                        .HasDatabaseName("ID_Usuarios1");

                    b.HasIndex(new[] { "FechaAcceso" }, "IX_FechaAcceso");

                    b.ToTable("registro_accesos", (string)null);
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Soporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<int>("IdUsuarios")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_USUARIOS");

                    b.Property<int>("IdUsuariosNavigationId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("IdUsuariosNavigationId");

                    b.HasIndex(new[] { "IdUsuarios" }, "ID_USUARIOS")
                        .HasDatabaseName("ID_USUARIOS1");

                    b.ToTable("soportes", (string)null);
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Ubicacione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DireccionFormateada")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("decimal(10,8)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("decimal(11,8)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("ubicaciones", (string)null);
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acesso")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<long>("Documento")
                        .HasColumnType("bigint(20)");

                    b.Property<int?>("IdUbicacion")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_Ubicacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Permisos")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("PrefijoTelefono")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Rut")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("IdUbicacion");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.UsuariosPropiedade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdPropiedad")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_Propiedad");

                    b.Property<int>("IdPropiedadNavigationId")
                        .HasColumnType("int(11)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int(11)")
                        .HasColumnName("ID_Usuario");

                    b.Property<int>("IdUsuarioNavigationId")
                        .HasColumnType("int(11)");

                    b.Property<string>("RolEnPropiedad")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RolEnPropiedad");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("IdPropiedadNavigationId");

                    b.HasIndex("IdUsuarioNavigationId");

                    b.ToTable("usuarios_propiedades", (string)null);
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Almacenan", b =>
                {
                    b.HasOne("ProyectoMSD.Modelos.Dispositivo", "IdDispositivosNavigation")
                        .WithMany()
                        .HasForeignKey("IdDispositivosNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoMSD.Modelos.Espacio", "IdEspaciosNavigation")
                        .WithMany("Almacenans")
                        .HasForeignKey("IdEspaciosNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdDispositivosNavigation");

                    b.Navigation("IdEspaciosNavigation");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Configuracione", b =>
                {
                    b.HasOne("ProyectoMSD.Modelos.Dispositivo", "IdDispositivosNavigation")
                        .WithMany("Configuraciones")
                        .HasForeignKey("IdDispositivos")
                        .IsRequired()
                        .HasConstraintName("configuraciones_ibfk_1");

                    b.HasOne("ProyectoMSD.Modelos.Usuario", "IdUsuariosNavigation")
                        .WithMany("Configuraciones")
                        .HasForeignKey("IdUsuariosNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdDispositivosNavigation");

                    b.Navigation("IdUsuariosNavigation");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Dispositivo", b =>
                {
                    b.HasOne("ProyectoMSD.Modelos.Espacio", "Espacio")
                        .WithMany()
                        .HasForeignKey("IdEspacio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Espacio");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Espacio", b =>
                {
                    b.HasOne("ProyectoMSD.Modelos.Propiedade", "IdPropiedadesNavigation")
                        .WithMany("Espacios")
                        .HasForeignKey("IdPropiedades")
                        .IsRequired()
                        .HasConstraintName("espacios_ibfk_1");

                    b.HasOne("ProyectoMSD.Modelos.Ubicacione", null)
                        .WithMany("Espacios")
                        .HasForeignKey("UbicacioneId");

                    b.Navigation("IdPropiedadesNavigation");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Notificacion", b =>
                {
                    b.HasOne("ProyectoMSD.Modelos.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IdUsuarios")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_notificaciones_usuarios");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Propiedade", b =>
                {
                    b.HasOne("ProyectoMSD.Modelos.Usuario", "IdUsuariosNavigation")
                        .WithMany("Propiedades")
                        .HasForeignKey("IdUsuariosNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoMSD.Modelos.Ubicacione", null)
                        .WithMany("Propiedades")
                        .HasForeignKey("UbicacioneId");

                    b.Navigation("IdUsuariosNavigation");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.RegistroAcceso", b =>
                {
                    b.HasOne("ProyectoMSD.Modelos.Usuario", "IdUsuariosNavigation")
                        .WithMany("RegistroAccesos")
                        .HasForeignKey("IdUsuarios")
                        .IsRequired()
                        .HasConstraintName("registro_accesos_ibfk_1");

                    b.Navigation("IdUsuariosNavigation");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Soporte", b =>
                {
                    b.HasOne("ProyectoMSD.Modelos.Usuario", "IdUsuariosNavigation")
                        .WithMany("Soportes")
                        .HasForeignKey("IdUsuariosNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdUsuariosNavigation");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Usuario", b =>
                {
                    b.HasOne("ProyectoMSD.Modelos.Ubicacione", "IdUbicacionNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdUbicacion")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_usuarios_ubicaciones");

                    b.Navigation("IdUbicacionNavigation");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.UsuariosPropiedade", b =>
                {
                    b.HasOne("ProyectoMSD.Modelos.Propiedade", "IdPropiedadNavigation")
                        .WithMany("UsuariosPropiedades")
                        .HasForeignKey("IdPropiedadNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoMSD.Modelos.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuariosPropiedades")
                        .HasForeignKey("IdUsuarioNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPropiedadNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Dispositivo", b =>
                {
                    b.Navigation("Configuraciones");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Espacio", b =>
                {
                    b.Navigation("Almacenans");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Propiedade", b =>
                {
                    b.Navigation("Espacios");

                    b.Navigation("UsuariosPropiedades");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Ubicacione", b =>
                {
                    b.Navigation("Espacios");

                    b.Navigation("Propiedades");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ProyectoMSD.Modelos.Usuario", b =>
                {
                    b.Navigation("Configuraciones");

                    b.Navigation("Notificaciones");

                    b.Navigation("Propiedades");

                    b.Navigation("RegistroAccesos");

                    b.Navigation("Soportes");

                    b.Navigation("UsuariosPropiedades");
                });
#pragma warning restore 612, 618
        }
    }
}
